### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by achingbrain** [fails-components/webtransport#100]
The test suite is one function that reuses the same server and runs the tests sequentially.  This can be improved - would you accept a PR that uses a test framework, splits the tests into separate files so we can run them individually and with set-up/tear-down steps for better isolation, etc?

My(weak) preference is for [mocha](https://mochajs.org/), but I see there's now a [built-in test framework](https://nodejs.org/api/test.html) in the most recent node, which might be fun to experiment with, but it will restrict development to node v18.0+, which might not be a big deal in the long run, as long as the built binaries still run on older versions 🤷.

**Comment by martenrichter** [comment]
Yes, sounds good, but I think for some time both test frameworks should run in parallel (just to be sure, the test saves me a lot of time, when the quiche lib is updated weekly).

Regarding the framework this is tricky. When I wrote the test I also found mocha, but the learning curve was not fitting into my time budget (for me it is a hobby and this packet is just a requirement for my bigger hobby project, but I like to share code).
Anyway, I think it is a good idea to run the tests on the current node LTS version, as I will always develop on node LTS.
So this a vote for `mocha` but in the long time run the internal would be good (which is still experimental)
