### ISSUE TITLE
Finding icu4c during build on M1 Macs

### ISSUE THREAD

**Issue by achingbrain** [fails-components/webtransport#105]
When I build master on my M1 Mac it fails to find `icu4c` with:

```
CMake Error at /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Failed to find all ICU components (missing: ICU_LIBRARY) (found version
  "70.1")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/FindICU.cmake:335 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:38 (find_package)
```

It starts to work if I change [this line](https://github.com/fails-components/webtransport/blob/master/CMakeLists.txt#L34) in `CMakeLists.txt` from:

```
                SET(ICU_ROOT "/opt/homebrew/icu4c")
```

to:

```
                SET(ICU_ROOT "/usr/local/opt/icu4c")
```

I don't know if this is down to my homebrew version or something else but as CI seems happy with the config I'm posting this here in case it helps someone else in the future.

```console
% brew --version
Homebrew 3.6.7
```

In that file the `ICU_ROOT` gets set to `/usr/local/opt/icu4c` if the architecture is `x86_64` which it's not in my case so maybe the config is expecting an older homebrew version?

**Comment by achingbrain** [comment]
Ah, ok fine - if the current config is just a guess then I can provide insights as I have an M1 Mac.  Will submit a PR to change it.

**Comment by martenrichter** [comment]
Perfect, please try compilation for arm and intel, if everything is correctly detected. M1 are not available as runners, and actually developing using the CI/CD is a pain, every test needs a commit and a wait of 10-20 minutes.

**Comment by achingbrain** [comment]
> As I understood, "/usr/local/opt/icu4c" should only apply to intel architecture builds.

You might be right actually:

```console
% file /usr/local/opt/icu4c/bin/icuinfo
/usr/local/opt/icu4c/bin/icuinfo: Mach-O 64-bit executable x86_64
```

Is there a way to get it to search both locations?

**Comment by martenrichter** [comment]
No, but you can try if you can detect to the build-arch and the arch it is building on and send a PR. This seems not to work as intended

**Comment by martenrichter** [comment]
And may be the problem is that you did not install icu4c for arm?

**Comment by achingbrain** [comment]
> And may be the problem is that you did not install icu4c for arm

That's possible, all I did was `brew install icu4` so it should probably handle both?

It seems it'll happily build an `arm64` binary using a `x86_64` `icu4`.

**Comment by martenrichter** [comment]
> That's possible, all I did was `brew install icu4` so it should probably handle both?

Do not know, I do not have a mac and I am not really familiar with brew, sorry?

> It seems it'll happily build an `arm64` binary using a `x86_64` `icu4`.

That should not work, but be aware, that there was a 1-2 weeks ago a change in libquic, where I needed to change the way icu is handled on mac.

**Comment by achingbrain** [comment]
> That should not work

Apple have been pretty good with getting `arm64` things to run with `x84_64` and vice versa, maybe it's that.  Sometimes I forget I'm on a complete different architecture to my last computer.

**Comment by martenrichter** [comment]
But I got a linker error when I mixed libs for icu on the weekend....

**Comment by martenrichter** [comment]
The lib is not converted back to use a static build, directly build from a git repo. So the problem does not occur anymore.
