### ISSUE TITLE
Remote host/ip

### ISSUE THREAD

**Issue by achingbrain** [fails-components/webtransport#114]
I need to discover the address/port of the peer at the other end of a session on the http3server side, similar to `net.Socket`'s [.remoteAddress](https://nodejs.org/dist/latest-v18.x/docs/api/net.html#socketremoteaddress) and [.remotePort](https://nodejs.org/dist/latest-v18.x/docs/api/net.html#socketremoteport) fields.

I had a little dig around but I couldn't spot anything obvious - is this something libquiche exposes that could be passed to js in the `Http3WTSessionVisitor` event?

**Comment by martenrichter** [comment]
I think there is, but I am not sure if it is a good idea to add it to the Visitor event.  (I try to have a look).
It can change during the connection...

**Comment by martenrichter** [comment]
https://github.com/google/quiche/blob/ecc958b60c795f25ed5786c00544e4131f2cb5b0/quiche/quic/core/quic_connection.h#L793
here it is. You may also want to look into
https://github.com/google/quiche/blob/main/quiche/quic/core/http/end_to_end_test.cc
these are the unit tests for webtransport. Actually, it was my starting point into understand the lib, but not an easy endeavour.
