### ISSUE TITLE
host vs hostname?

### ISSUE THREAD

**Issue by achingbrain** [fails-components/webtransport#131]
I may be reading this wrong, but `Http3ClientJS` [accepts a `hostname` option](https://github.com/fails-components/webtransport/blob/master/src/http3client.cc#L1342) while `Http3ServerJS` [accepts a `host` option](https://github.com/fails-components/webtransport/blob/master/src/http3server.cc#L166).  Both values appear to default to `"localhost"`.

In JS land their counterparts are both [subclasses of `Http3WebTransport`](https://github.com/fails-components/webtransport/blob/master/lib/transport.js#L9-L20) so the `args` type for that class needs both `host` and `hostname` properties which looks a little weird.

Can it be standardised to `host`?  This would be similar to [`server.listen(options[, callback])`](https://nodejs.org/api/net.html#serverlistenoptions-callback) in node core which accepts a `host` option.

**Comment by martenrichter** [comment]
Well, the client API is totally internal. So if you like you can change it to the value of the server.
I think the difference is historical and comes, from the decomposition of the URL in the client and the respective names in gurl and now on the js side URL object, where this property is called hostname.
