### ISSUE TITLE
WebTransportError: Opening handshake failed

### ISSUE THREAD

**Issue by darrachequesne** [fails-components/webtransport#166]
Hi! I'm trying to use the library, but can't achieve connection on Chrome (Version 110.0.5481.177, Ubuntu 20.04).

I've created a sample project reproducing the issue: https://github.com/darrachequesne/webtransport-example

I've taken a look at https://github.com/fails-components/webtransport/issues/76, but it does not seem to be related to the certificate.

It works with the Node.js client though. Thanks in advance!

**Comment by martenrichter** [comment]
And, what is the error message on the browser side?

**Comment by martenrichter** [comment]
And can you replace the certificate generating code, with the one we use in our unit tests.

**Comment by darrachequesne** [comment]
The error in the console

```
Failed to establish a connection to https://localhost:3001/echo: net::ERR_CONNECTION_REFUSED.
Uncaught (in promise) WebTransportError: Opening handshake failed.
```

The certificate is valid (10 days validity), according to Chrome:

![Screenshot from 2023-05-04 09-10-34](https://user-images.githubusercontent.com/13031701/236134964-f1648c8c-7cf5-44a3-8f09-b71666b55fbd.png)

![Screenshot from 2023-05-04 09-10-46](https://user-images.githubusercontent.com/13031701/236134982-112ae319-3ec9-4e2d-9548-7dc84add11a1.png)

I'll try with the code in the unit tests.

**Comment by martenrichter** [comment]
The error sounds more like a closed blocked port. Please check, which app is bound to which udp port.... 
And if the port in general is reachable. If you want to compile the binary yourself, I can also pinpoint you where to add debug output for seeing if someone tries to connect.

**Comment by darrachequesne** [comment]
That's weird, the port seems to be open:

```
$ node client.js
load webtransport binary: ../build/Release/webtransport.node
start GlobalEventLoop
createGlobalEventLoop
Waiting for client to be ready
wait for session
Client ready
Client created stream
```

With `netcat`:

```
$ nc -vz -u 127.0.0.1 3001
Connection to 127.0.0.1 3001 port [udp/*] succeeded!
```

Tested on Chrome (110.0.5481.177) and Chromium (112.0.5615.49), with Node.js v16.15.1 and v18.12.1.

I feel there is something obvious I am missing.

> If you want to compile the binary yourself, I can also pinpoint you where to add debug output for seeing if someone tries to connect.

Yes please.

**Comment by darrachequesne** [comment]
I have added a bunch of `"cout << "..." << endl;` but to no avail, the breakpoints you suggested are not reached...

Are you able to reproduce the issue with the example I provided above (https://github.com/darrachequesne/webtransport-example)? Or is it a problem with my own setup?

Else, is it possible that there is a compatibility issue with latest versions of chromium, as is suggested [there](https://github.com/w3c/webtransport/issues/511#issuecomment-1547247351)?

**Comment by martenrichter** [comment]
> I have added a bunch of `"cout << "..." << endl;` but to no avail, the breakpoints you suggested are not reached...
Ok interesting, if you are not hitting OnSocketEvent, then you get no UDP packet. So the UDP are not reaching your socket.
So it might be a network binding to the wrong port with the wrong address.  So it looks like a firewall problem.

> 
> Are you able to reproduce the issue with the example I provided above (https://github.com/darrachequesne/webtransport-example)? Or is it a problem with my own setup?
I am only doing programming in my free time on weekends, and this weekend did not have enough time.
So sorry, I did not find the time.
> 
> Else, is it possible that there is a compatibility issue with latest versions of chromium, as is suggested [there](https://github.com/w3c/webtransport/issues/511#issuecomment-1547247351)?
No I have run it against Chrome Canary on Sunday.

**Comment by martenrichter** [comment]
May be look into the server start phase:
https://github.com/fails-components/webtransport/blob/320550b99bfdffe5e2de5ce84a5a03e196a0ab4f/src/http3server.cc#L139

**Comment by martenrichter** [comment]
I am now trying it. First thing to note, it seems not to work with localhost, using a normal ip address it works. I will check if this is a problem in the webtransport module.
After this, it is complaining about the certificate. This is not astonishing, since it is not a known certificate authority, so you must pass the fingerprint, which is not part of the example. The ignore certificate stuff, I personally never got to work with chrome, but since I always use fingerprints it is not an issue for me.

**Comment by martenrichter** [comment]
I have checked localhost. The code of the library translates it fine to 127.0.0.1 . However, the browser seems to have no clue what localhost ist, but it knows 127.0.0.1 . Could be a bug in chromium, would not be the first.

**Comment by darrachequesne** [comment]
It does indeed seem to be linked to the usage of "localhost". If I create an alias in my `/etc/hosts` file:

```
$ cat /etc/hosts
127.0.0.1   localhost
127.0.0.1   example.com
```

And create a self-signed certificate for this domain, then I'm able to successfully reach the server :rocket: 

In case anyone is interested, here is the diff: https://github.com/darrachequesne/webtransport-example/commit/46a90982152afa0e171678f32050f465b65ee163

Thanks a lot for your help :+1:

**Comment by darrachequesne** [comment]
For future readers, using `127.0.0.1` instead of `localhost` works: https://github.com/darrachequesne/webtransport-example

`generate_cert.sh`

```sh
#!/bin/bash
openssl req -new -x509 -nodes \
    -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
    -out cert.pem -keyout key.pem \
    -subj '/CN=127.0.0.1'
```

`open_chrome.sh`

```sh
#!/bin/bash
HASH=`openssl x509 -pubkey -noout -in cert.pem |
   openssl pkey -pubin -outform der |
   openssl dgst -sha256 -binary |
   base64`

/opt/google/chrome/chrome \
    --origin-to-force-quic-on=127.0.0.1:3000 \
    --ignore-certificate-errors-spki-list=$HASH \
    https://localhost:3000
```

No alias needed :rocket:

`new WebTransport("https://localhost:3000/echo");` doesn't work though, which is a bit weird.

**Comment by martenrichter** [comment]
> `new WebTransport("https://localhost:3000/echo");` doesn't work though, which is a bit weird.

And this may be a bug in chrome, or in my certificate-checking code.
