### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by darrachequesne** [fails-components/webtransport#175]
Hi! I've noticed that there are a few `console.log()` in the source files. Would you consider a PR which would use [`debug`](https://www.npmjs.com/package/debug) or [`util.debug()`](https://nodejs.org/api/util.html#utildebugsection) instead?

**Comment by martenrichter** [comment]
There is one open pull request, that already changes logging. It is the run tests in browser test. Once 115 chromium enters the playwright test suite, it will probably be merged, since a bug in chromium is preventing this.
