### ISSUE TITLE
Types missing on version 1.0.4

### ISSUE THREAD

**Issue by endel** [fails-components/webtransport#233]
Hi @martenrichter, congrats on the latest update 👏  I've just tried it out and noticed TypeScript type definitions are missing, though:

<img width="742" alt="Screenshot 2023-12-30 at 10 32 44" src="https://github.com/fails-components/webtransport/assets/130494/19b12b83-0500-4dea-b195-3a2a182c7df3">

Cheers!

**Comment by martenrichter** [comment]
Ok, I was so happy, that the compiler did not throw any errors at me. 
I hope, I have fixed it, in the branch for dealing with firefox unit tests.
Sorry for this, but the problem with typescript is that I do not use it so it is very likely to break.
You can test if it makes sense for you. I may release a new bugfix release this year.
