### ISSUE TITLE
getting Opening handshake failed on nodejs

### ISSUE THREAD

**Issue by maa105** [fails-components/webtransport#260]
Hello I am trying to use this module with a Quic server (not localhost) the server has an IP and a port but I am getting:
`Opening handshake failed.`
Ps I am not using a browser but rather nodejs and am importing `WebTransport` from `@fails-components/webtransport/lib/webtransport.node`
am i doing anything wrong?

I checked https://github.com/fails-components/webtransport/issues/166 but it doesnt seem to be related as he is trying to connect from the browser and what solved it to him was using ip instead of localhost which I am doing since the server I am connecting to is not on localhost

**Comment by martenrichter** [comment]
What do you mean by QuicServer? It must be a server speaking http/3 and webtransport, quic alone is not enough,

**Comment by maa105** [comment]
A server implementing Quic protocol

**Comment by martenrichter** [comment]
But quic protocol enough is not sufficient. WebTransport is not Quic. WebTransport is Quic with http/3 and special WebTransport semantics, so this can not worrk

**Comment by maa105** [comment]
Thank you for tolerating my ignorance on the topic. If you can extend your tolarance a small branch is it possible to to connect to a Quic server using your package. If not if you know a thread that can help me please point me to it.

Thanks

**Comment by martenrichter** [comment]
No, it is not possible.

**Comment by martenrichter** [comment]
At least, if it is not a quicserver with support for webtransport over http/3
