### ISSUE TITLE
Firefox cannot dial @fails-components/webtransport server

### ISSUE THREAD

**Issue by achingbrain** [fails-components/webtransport#265]
Here's a [simple echo server](https://github.com/achingbrain/webtransport-echo-server)

```console
$ git clone https://github.com/achingbrain/webtransport-echo-server.git
$ cd webtransport-echo-server
$ npm i
$ npm run browser

> webtransport-echo-server@1.0.0 browser
> node browser.js

Paste the following code into https://codepen.io or similar:

(async function main ()  {
  console.info('CLIENT create session')
// ...more code here
```

Running the code in Chrome yields the expected* result:

```
"CLIENT create session"
"CLIENT wait for session"
"CLIENT session ready"
"CLIENT create bidi stream"
"CLIENT get writer"
"CLIENT wait for writer"
"CLIENT write"
"CLIENT close writer"
"CLIENT read from stream"
"CLIENT got from stream" // [object Object] 
{
  "done": false,
  "value": {
    "0": 0,
    "1": 1,
    "2": 2,
    "3": 3
  }
}
"CLIENT read from stream"
```

When running in Firefox Nightly (125.0a1 (2024-03-05) (64-bit)), the session never becomes ready:

```
"CLIENT create session"
"CLIENT wait for session"
```

----

\* = the read stream doesn't end, but it won't until #256 ships

**Comment by martenrichter** [comment]
But the firefox units worked so far. (But it is an older Firefox version).
Can you test it in the context of the Firefox unit test to figure out if it works there? (I made some analogue to your Chromium tests).
Is it the nightly including:
https://bugzilla.mozilla.org/show_bug.cgi?id=1873263
https://bugzilla.mozilla.org/show_bug.cgi?id=1872496
?

And then the question arises, if it is on my side or the browser side.  (I learned that it is often not the fault of the package.)

**Comment by achingbrain** [comment]
Ah, that first one was only merged about five hours ago, it's probably not in nightly yet - I'll check back at the end of the week.

**Comment by martenrichter** [comment]
And I would be surprised if it did not work with the node.js server as I wrote the firefox patch testing against the unit test server of this package.

**Comment by achingbrain** [comment]
Fingers crossed.

**Comment by achingbrain** [comment]
Uncross your fingers, it all works with today's nightly!

**Comment by martenrichter** [comment]
If you do not have a certificate signed by a chain based on a root certificate.
Please note, Firefox had a bug with serverCertificateHashes and will work again with version 136.

**Comment by guest271314** [comment]
> If you do not have a certificate signed by a chain based on a root certificate.

I don't. I'm using self-signed certificate per this https://github.com/GoogleChrome/samples/blob/gh-pages/webtransport/webtransport_server.py#L40-L75 since `QuicTransport` https://github.com/guest271314/quictransport, before there was a formal `WebTransport`.

Insane how this has so many roadblocks for local usage.

**Comment by guest271314** [comment]
>   Firefox had a bug with serverCertificateHashes and will work again with version 136. 

I'm on Nightly 138. Here's the bug they closed https://bugzilla.mozilla.org/show_bug.cgi?id=1955877, referring me to this https://github.com/FiloSottile/mkcert. 

Will the approach used in `certificate.js` in the linked repository work?

**Comment by guest271314** [comment]
I went ahead and bundled `certificate.js` to a single script with 

```
bun build --target=node certificate.js --outfile=wt-certificate-bundle.js
```

I'm using Deno's WebTransport server (and client) implementation.

```
import certificates from "./cert.json" with {type:"json"};

const serverCertificateHashes = [{
      algorithm: 'sha-256',
      value: Uint8Array.from(atob(btoa(String.fromCodePoint(...certificates[0].hash.digest))), (m) => m.codePointAt(0))
}];

const server = new Deno.QuicEndpoint({
  hostname: "localhost",
  port: 4433,
});
const listener = server.listen({
  cert: certificates[0].pem,
  key: certificates[0].privateKey,
  alpnProtocols: ["h3"],
});
```

Works on Chromium Version 136.0.7088.0 (Developer Build) (64-bit). Works on Deno canary 2.2.5+d07b7ea (canary, release, x86_64-unknown-linux-gnu).
Does not work on Firefox Nightly 138.0a1 (2025-03-24) (64-bit), at least not running in `console`.

**Comment by martenrichter** [comment]
I always use serverCertificateHashes with self-signed certificates. I never got the other way to work. You can see how it is done in the test code of this repo.

**Comment by guest271314** [comment]
> I always use serverCertificateHashes with self-signed certificates. I never got the other way to work. You can see how it is done in the test code of this repo.

I did get the code in the linked repository to work on Firefox. I didn't try further than just what index.js does. 

Of course, Firefox ain't Chromium. They got some CSP and CORS stuff going on. I just try `WebTransport` constructor in random Web pages in `console`. Though in theory the Deno WebTransport server should work. 

The server. 

After I compiled the `certificates.js` to a single bundle I converted the resulting JavaScript object to JSON, so I only have to do that once. E.g.,

```
const certificates = [
  {
    "privateKey": "-----BEGIN PRIVATE KEY ...
```

```
import certificates from "./cert.json" with { type: "json" };

const serverCertificateHashes = [{
  algorithm: "sha-256",
  value: Uint8Array.from(
    atob(btoa(String.fromCodePoint(...certificates[0].hash.digest))),
    (m) => m.codePointAt(0),
  ),
}];

const server = new Deno.QuicEndpoint({
  hostname: "localhost",
  port: 4433,
});
const listener = server.listen({
  cert: certificates[0].pem,
  key: certificates[0].privateKey,
  alpnProtocols: ["h3"],
});

let requests = 0;
async function handle(wt) {
  try {
    console.log(wt);
    const encoder = new TextEncoder();
    await wt.ready;
    for await (
      const { readable, writable } of wt.incomingBidirectionalStreams
    ) {
      for await (const value of readable.pipeThrough(new TextDecoderStream())) {
        console.log(value);
        await new Response(value.toUpperCase()).body
          .pipeTo(writable, { preventClose: true });
      }
      await writable.close().then(() => console.log("writable close"));

      console.log(writable);
      await new Promise((r) => setTimeout(r));
      wt.close();
      break;
    }
  } catch (e) {
    console.log(e);
    console.trace();
  } finally {
    return wt.closed.then(() => ({
      code: 0,
      reason: `Done streaming request ${requests++}`,
    }));
  }
}

for await (const conn of listener) {
  const wt = await Deno.upgradeWebTransport(conn);
  try {
    handle(wt)
      .then((promise) => console.log(promise))
      .catch(console.error);
  } catch (e) {
    console.log(e);
  } finally {
    continue;
  }
}
server.close();

```

The client

```
import certificates from "./cert.json" with { type: "json" };

const serverCertificateHashes = [{
  algorithm: "sha-256",
  value: Uint8Array.from(
    atob(btoa(String.fromCodePoint(...certificates[0].hash.digest))),
    (m) => m.codePointAt(0),
  ),
}];

// console.log(serverCertificateHashes);

//console.log([...certHash]);
const client = new WebTransport(
  `https://localhost:4433/path`,
  {
    serverCertificateHashes,
  },
);

await client.ready;
const encoder = new TextEncoder();
let controller;
const abortable = new AbortController();
const {
  signal,
} = abortable;
const { readable, writable } = await client.createBidirectionalStream();
// const writer = writable.getWriter();
const stream = readable.pipeThrough(new TextDecoderStream())
  .pipeTo(
    new WritableStream({
      start(c) {
        controller = c;
      },
      write(value, c) {
        console.log(value);
      },
      close() {
        console.log("WritableStream close");
      },
      abort(reason) {
        console.log({ reason });
      },
    }, { highWaterMark: 1 }),
    { signal },
  ).catch((e) => e.message);

await new Response(encoder.encode("x".repeat(1024 ** 2))).body
  .pipeTo(writable);

if (!navigator.userAgent.includes("Deno")) {
  await Promise.allSettled([client.closed, stream])
    .then(console.log);
} else {
  if (navigator.userAgent.includes("Deno")) {
    // Deno doesn't close on writer.close()
    await new Promise((r) => setTimeout(r, 7));
    //console.log(abortable);
    client.close();
    await Promise.allSettled([client.closed, stream])
      .then(console.log);
  }
}
```

At the command line

```
...XXXXXXXXXXXXXXXXXXXXXXXXX
{
  reason: NotConnected: connection lost
    at async Object.pull (ext:deno_web/06_streams.js:962:27) {
    name: "NotConnected",
    code: "ENOTCONN"
  }
}
[
  {
    status: "fulfilled",
    value: [Object: null prototype] { closeCode: 0, reason: "" }
  },
  { status: "fulfilled", value: "connection lost" }
]

```

In this Web page in `console`, with `certificates` hardcoded as JSON

![Image](https://github.com/user-attachments/assets/618742ff-2afe-4f47-9bc1-adbe58c02c26).

Firefox 138. Nothing...

![Image](https://github.com/user-attachments/assets/8958b701-86bf-4679-af1e-3268847470e8)

I'm not shocked. Firefox was still working on specification conformant `HTMLMediaElement.captureStream()` the last time I checked.

It has been Chromium for development, Firefox for watchin videos for a while, now. I still do at least try to vet Web compatibility.

This is just far too cumbersome. Not even an interjection by anybody along the way that maybe there should be an option for developers to test the gear without  roadblocks.

**Comment by guest271314** [comment]
Moreover. I don't think the specification mandates `serverCertificateHashes`. It's just an *option*. 

> 8 Let serverCertificateHashes be [options](https://w3c.github.io/webtransport/#dom-webtransport-webtransport-url-options-options)’s [serverCertificateHashes](https://w3c.github.io/webtransport/#dom-webtransportoptions-servercertificatehashes) if it exists, and null otherwise.

The Deno WebTransport server works just fine on Chromium without `serverCertificateHashes`.

Maybe I should test the client in this repository connecting to the Deno WebTransport server without `serverCertificateHashes` option. I didn't start using that option until I decided to see what happens in Firefox Nightly using the same client I use in Chromium Developer Build.

**Comment by guest271314** [comment]
I got the example in the linked repository working on Firefox 138 - using @fails-components/webtransport.

![Image](https://github.com/user-attachments/assets/738614be-4d83-42ec-9809-c54b3b95b3d2)

Deno's WebTransport server works with generated certificate, or no certificate hashes with `--ignore-certificate-errors-spki-list=...`, on Chromium 136.

![Image](https://github.com/user-attachments/assets/079e92e6-529a-40e8-879b-a878d6c2b795)

I have not been able to get Deno's WebTransport server and Firefox to do anything but hang - using any approach. Firefox bug responder suggested using mkcert. To me, if @fails-components/webtransport with dynamic generation of certificate works using `node index`, `deno -A wt-server.js` should work, too.

![Image](https://github.com/user-attachments/assets/549047a7-647b-4550-8184-881604d64eaa)

**Comment by martenrichter** [comment]
I can not help you on this. I usually startup a debugger on firefox and inspect the C++ code step by step to find out what is wrong. Note that the validity period has to be less than 14 days and that not all signed methods are supported.

**Comment by martenrichter** [comment]
> > I can not help you on this.
> 
> That's fine. I just tested Firefox to see what happens, mainly. Your code works. That's an option I have.
> 
> I was reading part of your code yesterday and saw you have an HTTP/2 implementation within the base?

Yes, I have all in the base that requires just browser or node.js. The separate packages are for implementations, that require big binary packages for node.js . (just one in the moment). 

>I think I should be able to do WebTransport over TCP using `TCPServerSocket`. I'm just stuck at where to start.

The problem is that I am building on top of the http/2 server and client of node.js. As this is a binary implementation, you would need your own http/2 implementation in js or wasm. So it is not easy. 
Also, note that no browser has implemented the http/2 protocol so far. (There is some progress on quiche (chromium) and firefox, but so far not all bits are put together.)

**Comment by guest271314** [comment]
> Yes, I have all in the base that requires just browser

Right now I'm just trying to learn the protocol, in code. Since I'll be implementing in JavaScript, ideally in JavaScript. If not, I can compile to WASM then to JavaScript with Binaryen's `wasm2js`.

Links, and notes you might still have, would be helpful.

> Also, note that no browser has implemented the http/2 protocol so far. (There is some progress on quiche (chromium) and firefox, but so far not all bits are put together.)

Yeah. Full-duplex streaming over HTTP/2 with WHATWG Fetch *is* possible using `node`, `deno`, and `bun`. The browser doesn't fulfill until all bytes are read in the server or `writable` closes. 

So I have resorted to a hack on Chromium which provides a means to piggy-back on to the `fetch()` from a `WindowClient` intercepted by `fetch` event in a `ServiceWorker` , which appears to use Mojo internally, not necessarily HTTP/2. See [[chromium-dev] Is HTTP/2 or HTTP/3 used internally for onfetch between a ServiceWorker and WindowClient?](https://groups.google.com/a/chromium.org/g/chromium-dev/c/I_hfhGILbDc/m/X7bkVwbDBAAJ?utm_medium=email&utm_source=footer&pli=1)

> This seems likely to be https://chromium.googlesource.com/chromium/src/+/main/mojo/README.md

I understand WebTransport over HTTP/2 is just getting started, kind of.


Right now I'm just trying to successfully complete a `fetch()` request over HTTP/2 to the HTTP server using `TCPServerSocket` in the browser now. Just because it hasn't been done, and is there to do. Currently the closest I have gotten is `Transfer-Encoding: chunked`. Regular HTTP request to the server in the browser succeeds.

![Image](https://github.com/user-attachments/assets/3999dadb-58c8-407a-bfd8-19fb4fe02707)

That is trying to get something like this to work.

```
fetch("http://0.0.0.0:44818", {
  method: "post",
  duplex: "half",
  body: new Blob(["test"]).stream(),
  headers: {
    "Access-Control-Request-Private-Network": true,
  },
})
  .then((r) => r.text()).then((text) =>
    console.log({
      text,
    })
  ).catch(console.error);
```

Handle the `OPTIONS` request, maybe even try Upgrade, even though allegedly browsers don't support that for HTTP/2.

Right now I get the `OPTIONS` request in the server, just not sure how to write HTTP/2 headers for response. 

```
POST http://0.0.0.0:44818/ net::ERR_H2_OR_QUIC_REQUIRED
```

![Image](https://github.com/user-attachments/assets/c2ff7773-9048-4486-9528-aed64a0d2121)

I'm stuck on writing the HTTP/2 headers (frames, etc).

**Comment by guest271314** [comment]
@achingbrain FWIW Some code that started with your webtransport-echo-server code https://github.com/guest271314/webtransport-js-bundle
