### ISSUE TITLE
webtransport over http2 client has invalid signature call

### ISSUE THREAD

**Issue by ice-cronus** [fails-components/webtransport#269]
[here](https://github.com/fails-components/webtransport/blob/master/main/lib/http2/node/client.js#L49)
Signature is (hostname, cert) as it is called [with 2 parameters](https://nodejs.org/api/tls.html#tlscheckserveridentityhostname-cert)

**Comment by martenrichter** [comment]
Thanks for spotting this.
But actually, it is never called from node.js as the following issue:
https://github.com/nodejs/node/issues/49841
prevents a usage directly in node.js's verification step,
Instead, I currently use a workaround that closes the connection if the certificate is invalid, but during connection, every certificate is accepted.
