### ISSUE TITLE
Support multiple domains (SNICallback)

### ISSUE THREAD

**Issue by Aviv1000** [fails-components/webtransport#278]
Assuming you are running multiple domains with different SSL certificates, is it currently not possible to implement something like this?

**Comment by martenrichter** [comment]
I am afraid not and I have no plans to implement it.  (Anyway, PRs would be welcome but would be needed for all transports (http3 via quiche and http2 via node)

However, I would assume that this is something a load balancer would handle better.
But I do not know if there are load balancers out there that support http3 and webtransport. (My best bet would be envoy). When time progresses, it would be best to use that http2 webtransport and let the load balancer handle the http2 and http3.
