### ISSUE TITLE
Uncaught error when quickly recreating sessions

### ISSUE THREAD

**Issue by alienself** [fails-components/webtransport#328]
Hi there,

I am getting an error when a connection is open and closed rapidly (only open for a second or two). I am basically refreshing the web page where the connection is established and after a few refresh the server crashes and I get the following error in the console:

```sh
node_modules/@fails-components/webtransport/lib/session.js:484
    const wtError = new WebTransportError(
                    ^

WebTransportError: Session closed (on process 58921) with code 0 and reason
    at HttpWTSession.onClose (/node_modules/@fails-components/webtransport/lib/session.js:484:21)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  [Symbol(Symbol.toStringTag)]: 'WebTransportError'
} 
```

Is there a way to catch this error or is this a bug with the library? 

I tried to wrap everything I could in try / catch statements like the following but nothing seems to help it.

```js
this._session.closed
	.then(() => {
		this._handleClose(true);
	})
	.catch((e: any) => {
		console.log("[Socket] Session closed with error! " + e);
		this._handleClose(true);
	});

try {
	await this._session.ready;
} catch (error) {
	console.log("error", error)
}
```

**Comment by martenrichter** [comment]
The error from line 484 goes into the streams that you have opened (or that arrived and that you did not fetch), so send and receive streams etc.. So, you must make sure to catch the errors from the streams you get. I hope this helps.

**Comment by alienself** [comment]
Thank you very much for this quick response! You were right, I forgot a catch when writing to the stream's writer. All good!
