### ISSUE TITLE
SIGSEGV / EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by benbenz** [fails-components/webtransport#4]
Hi Marten,
Finally managed to catch this sigsegv error ... It occurs line 319 of `http3wtsessionvisitor.h`, this call:

```
session_->SendOrQueueDatagram(std::move(slice));
```

It seems to happen if I use datagrams and disconnect. Otherwise, the library has been acting really nice !
I think the session is invalid here, but the buffer of the slice seems to be of size 0 as well.

Callstack:
```
quic::Http3WTSession::writeDatagramInt(char*, unsigned long, Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >*) (/Users/benoit/dev/webtransport/src/http3wtsessionvisitor.h:319)
quic::Http3WTSession::writeDatagram(Nan::FunctionCallbackInfo<v8::Value> const&)::'lambda'()::operator()() const (/Users/benoit/dev/webtransport/src/http3wtsessionvisitor.h:245)
decltype(static_cast<quic::Http3WTSession::writeDatagram(Nan::FunctionCallbackInfo<v8::Value> const&)::'lambda'()&>(fp)()) std::__1::__invoke<quic::Http3WTSession::writeDatagram(Nan::FunctionCallbackInfo<v8::Value> const&)::'lambda'()&>(quic::Http3WTSession::writeDatagram(Nan::FunctionCallbackInfo<v8::Value> const&)::'lambda'()&) (/Users/benoit/dev/llvm/clang+llvm-14.0.0-x86_64-apple-darwin/include/c++/v1/type_traits:3640)
void std::__1::__invoke_void_return_wrapper<void, true>::__call<quic::Http3WTSession::writeDatagram(Nan::FunctionCallbackInfo<v8::Value> const&)::'lambda'()&>(quic::Http3WTSession::writeDatagram(Nan::FunctionCallbackInfo<v8::Value> const&)::'lambda'()&) (/Users/benoit/dev/llvm/clang+llvm-14.0.0-x86_64-apple-darwin/include/c++/v1/__functional/invoke.h:61)
std::__1::__function::__alloc_func<quic::Http3WTSession::writeDatagram(Nan::FunctionCallbackInfo<v8::Value> const&)::'lambda'(), std::__1::allocator<quic::Http3WTSession::writeDatagram(Nan::FunctionCallbackInfo<v8::Value> const&)::'lambda'()>, void ()>::operator()() (/Users/benoit/dev/llvm/clang+llvm-14.0.0-x86_64-apple-darwin/include/c++/v1/__functional/function.h:180)
std::__1::__function::__func<quic::Http3WTSession::writeDatagram(Nan::FunctionCallbackInfo<v8::Value> const&)::'lambda'(), std::__1::allocator<quic::Http3WTSession::writeDatagram(Nan::FunctionCallbackInfo<v8::Value> const&)::'lambda'()>, void ()>::operator()() (/Users/benoit/dev/llvm/clang+llvm-14.0.0-x86_64-apple-darwin/include/c++/v1/__functional/function.h:354)
std::__1::__function::__value_func<void ()>::operator()() const (/Users/benoit/dev/llvm/clang+llvm-14.0.0-x86_64-apple-darwin/include/c++/v1/__functional/function.h:507)
std::__1::function<void ()>::operator()() const (/Users/benoit/dev/llvm/clang+llvm-14.0.0-x86_64-apple-darwin/include/c++/v1/__functional/function.h:1184)
quic::Http3EventLoop::ExecuteScheduledActions() (/Users/benoit/dev/webtransport/src/http3eventloop.cc:127)
quic::Http3EventLoop::OnAsyncExecution() (/Users/benoit/dev/webtransport/src/http3eventloop.cc:115)
epoll_server::SimpleLibuvEpollServer::asynccallback(uv_async_s*) (/Users/benoit/dev/webtransport/platform/quiche_platform_impl/simple_libuv_epoll_server.cc:635)
uv__async_io (@uv__async_io:95)
uv__io_poll (@uv__io_poll:444)
uv_run (@uv_run:113)
epoll_server::SimpleLibuvEpollServer::WaitForEventsAndExecuteCallbacks() (/Users/benoit/dev/webtransport/platform/quiche_platform_impl/simple_libuv_epoll_server.cc:372)
quic::Http3EventLoop::Execute(Nan::AsyncBareProgressQueueWorker<quic::Http3ProgressReport>::ExecutionProgress const&) (/Users/benoit/dev/webtransport/src/http3eventloop.cc:108)
Nan::AsyncBareProgressQueueWorker<quic::Http3ProgressReport>::Execute() (/Users/benoit/dev/webtransport/node_modules/nan/nan.h:2201)
worker (@worker:97)
_pthread_body (@_pthread_body:83)
_pthread_start (@_pthread_body:3)
thread_start (@thread_start:7)
```

**Comment by martenrichter** [comment]
Hi,
I understand that the session object is probably gone.
The questions is, if the destructor of the Http3WTSession was called beforehand or the Visitor object. Or if the onCloseSession.., so that I may set session_ to nullptr and check this.
What I do not understand is, that you say the buffer size seems to be zero, since it comes from the javascript side, through the buffer or len argument, but maybe the whole Http3WTSession object is gone?
(I also do not know how to provoke the error, since I assume a lot of datagrams need to be send to achieve it).
It may be that I have to check on the js side if the session is closed....

Marten

**Comment by benbenz** [comment]
Hi
So I printed in the two destructors:
```
printf("Http3WTSession destructor %d %d\n",this,session_); // Session destructor
...
printf("sess unref %d\n",sessobj); // Visitor destructor
```

With the control channel as WebSocket (ws_ctrl) and the media channel as QUIC datagram (quic_media), I get this:
```
ws_ctrl:close
unpiping
stream destruct 5e34e80
Http3WTSession destructor 98803456 98802144
quic_media:close
sess unref 93355584
```

With the control channel as QUIC Stream (quic_ctrl) and the media channel as QUIC Datagrams (quic_media), I get the crash and this:
```
stream unref 5809eb0
stream unref 4f516f0
quic_media:close
unpiping
```

> What I do not understand is, that you say the buffer size seems to be zero, since it comes from the javascript side, through the buffer or len argument, but maybe the whole Http3WTSession object is gone?

Hmm that's true. I can't assure that the app is not sending a 0 length buffer but I don't think I have encountered this so far. I will try to look if there is this possibility in my app. It could mean that the whole thing is set to zero indeed? I think the address of the `session_` was something like 0x48. And everything in the object seemed to be "invalid".

**Comment by martenrichter** [comment]
Well this is a bit inconclusive, but I will now just secure the datagram path with checks for closed sessions....
Just one questions, why are you using datagrams for your channel, you know these are unrealiable and can be lost. (currently I have not implemented mechanism to delete old one, but according to spec  the lib and of course the browser should do this...).

**Comment by martenrichter** [comment]
So here are some untested potential fixes https://github.com/fails-components/webtransport/commit/0b9d8ed8f6a6174f04d8f53a819c9d258eefec40 . Basically I secured it analog to the stream stuff.

**Comment by benbenz** [comment]
> Well this is a bit inconclusive,

Yes I agree. I wanted to prepare a test bundle that reproduces it but I won't be able to do it before Monday.

> Just one questions, why are you using datagrams for your channel, you know these are unrealiable and can be lost. (currently I have not implemented mechanism to delete old one, but according to spec the lib and of course the browser should do this...).

Thanks yes I am aware. I was considering using them for small un-critical command packets and was just experimenting with the combinations. For media streaming I am actually not planning on using this indeed - I just encountered this crash here. But thanks for the info. I didn't know about non deleting old ones? I am not sure I understand

**Comment by benbenz** [comment]
Speaking of datagrams, can we consider very small and sparse packets to arrive as they've been sent ? Say the packets will be 8 bytes or so.

**Comment by martenrichter** [comment]
> > Well this is a bit inconclusive,
> 
> Yes I agree. I wanted to prepare a test bundle that reproduces it but I won't be able to do it before Monday.
Anyway, I commited some change, maybe I catched it.


>I didn't know about non deleting old ones? I am not sure I understand
Per spec one should record the time packets are received or send, and discard them if they are after a given time, which can be set, they are not send. This is currently not implemented, as well as, that the datagrams should always be send before the other packets... which also not implemented yet.

**Comment by martenrichter** [comment]
> Speaking of datagrams, can we consider very small and sparse packets to arrive as they've been sent ? Say the packets will be 8 bytes or so.

Of course not, speed of light is constant, and time is relative and network puts some delay.
Also, I am not sure if quiche handles datagrams first, or if I have to do it, and I do not.

**Comment by benbenz** [comment]
> > Speaking of datagrams, can we consider very small and sparse packets to arrive as they've been sent ? Say the packets will be 8 bytes or so.
> 
> Of course not, speed of light is constant, and time is relative and network puts some delay. Also, I am not sure if quiche handles datagrams first, or if I have to do it, and I do not. And there is a promise which is fullfilled after sending, you might use this.

Okay. Good to know! Ill run some experiments but the plan was to use QUIC stream anyhow. I also didnt know about the priority of processing, this is great information.

**Comment by benbenz** [comment]
> and time is relative and network puts some delay.

By "packets arrive as they've been sent", I actually meant for more "each packet arrive as one" meaning that they are not split if they have a relatively small size (few bytes). I have a byte ring buffer (as per our previous discussion) but if the packets do not arrive in order, this becomes really tricky to recompose the packets.

**Comment by benbenz** [comment]
> So here are some untested potential fixes [0b9d8ed](https://github.com/fails-components/webtransport/commit/0b9d8ed8f6a6174f04d8f53a819c9d258eefec40) . Basically I secured it analog to the stream stuff.

I think this did it ! :)

**Comment by martenrichter** [comment]
> > and time is relative and network puts some delay.
> 
> By "packets arrive as they've been sent", I actually meant for more "each packet arrive as one" meaning that they are not split if they have a relatively small size (few bytes). I have a byte ring buffer (as per our previous discussion) but if the packets do not arrive in order AND split, this becomes really tricky to recompose the packets.

Ok, that datagrams are guaranteed to arrive as they have been send, different to the stream. So no ring buffer necessary...
But it is not guaranteed, that they arrive at all.

**Comment by benbenz** [comment]
> Ok, that datagrams are guaranteed to arrive as they have been send, different to the stream. So no ring buffer necessary...
> But it is not guaranteed, that they arrive at all.

Okay. So 
- datagrams: packets arrive as they've been sent ("as one") + can be lost + order not guaranteed (?)
- stream: packets can be grouped + can't be lost (quic layer) + order guaranteed (quic layer) (?)

**Comment by martenrichter** [comment]
> > Ok, that datagrams are guaranteed to arrive as they have been send, different to the stream. So no ring buffer necessary...
> > But it is not guaranteed, that they arrive at all.
> 
> Okay. So
> 
> * datagrams: packets arrive as they've been sent ("as one") + can be lost + order not guaranteed (?)

I think the order should be guaranteed. They are just send one, and if they do not arrive no one cares...

> * stream: packets can be grouped + can't be lost (quic layer) + order guaranteed (quic layer) (?)
Yes, but it is actually not really a packet stream but a byte stream, where you write Buffers to, that is the cause of the splitting and merging.

I have now added code to priorize datagrams in writing, was relatively easy.
https://github.com/fails-components/webtransport/commit/8fb01e4a6e4e4710501172ef624bb350fdc4485c

**Comment by benbenz** [comment]
> I have now added code to priorize datagrams in writing, was relatively easy.

Awesome! I'll test latency etc. 👯‍♂️

**Comment by martenrichter** [comment]
I have also implemented byob, but since it uses pulling instead of pushing, it could have increased latency.
Therefore it is in its own branch, can you check it out with your real world application:
https://github.com/fails-components/webtransport/tree/byobreader
Thanks!

**Comment by benbenz** [comment]
Hello Marten
This is amazing.
I ran a simple ping test on the control channel for the two branches. Granted most of the latency is probably induced by my app at this stage, I got the following:
Default:
- 0.93 ms with STREAM
- 0.96 ms with DGRAM
Byob:
- 0.92 ms with STREAM 
- 0.95 ms with DGRAM

I didn't know if this would apply to datagrams so I ran the test for them as well.
The test is done by sending a binary ping command through the control channel and measuring the delay (performance.now) when the pong is received. I run 500 ping pongs and take the median latency.
I'm running local here to remove any network variation - let me know if the difference of performance would actually show more in real life network situation. 

The results seem to show most of the latency is probably induced by the app, as it is slightly counter-intuitive with what you said. Or maybe the gain of not creating buffers in NodeJS prove to be positive, compared to the loss of latency caused by the pulls ... ? (I actually didn't understand the difference of implementation you mentioned ...). I have also a not-so-optimized semi-ringbuffer on the control channel (client side) which I am planning on fixing today. I can send the new results later.

Side and unrelated question: should we assume we need to use a packet ringbuffer for both client and server side components - for QUIC Streams? So far I have used it only on the client side which hasn't been a problem (my command packets are really small and sparse) but would like to be compliant.

**Comment by benbenz** [comment]
I've got another question: if I wanted to also use BYOBReader on the client side. Let's say we pass a 4096 byte buffer to the reader ... can we assume the reader is using this as a RingBuffer? meaning we could potentially disregard the returned result from `read()` (aka the {done,value}) while assuming the reader appended the value in the buffer in a ringbuffer manner (overwriting eventually if we didn't read in time). We would just have to perform our our own READ_INDEX mechanism on the same buffer we provided .... ?

**Comment by martenrichter** [comment]
> Hello Marten This is amazing. I ran a simple ping test on the control channel for the two branches. Granted most of the latency is probably induced by my app at this stage, I got the following:
> 
> Default:
> 
>     * 0.93 ms with STREAM
> 
>     * 0.96 ms with DGRAM
> 
> 
> Byob:
> 
>     * 0.92 ms with STREAM
> 
>     * 0.95 ms with DGRAM
> 
> 
> I didn't know if this would apply to datagrams so I ran the test for them as well. 

No it does not apply to datagrams. It might also be only a different, if we have a high network load or higher bitrates. Currently it is inconclusive, I would not think the 1 ms difference is for real, it least it does not hurt for this test. Anyway nothing for me to decide yet.

> The test is done by sending a binary ping command through the control channel and measuring the delay (performance.now) when the pong is received. I run 500 ping pongs and take the median latency. I'm running local here to remove any network variation - let me know if the difference of performance would actually show more in real life network situation.
> 
> The results seem to show most of the latency is probably induced by the app, as it is slightly counter-intuitive with what you said. Or maybe the gain of not creating buffers in NodeJS prove to be positive, compared to the loss of latency caused by the pulls ... ? (I actually didn't understand the difference of implementation you mentioned ...). I have also a not-so-optimized semi-ringbuffer on the control channel (client side) which I am planning on fixing today. I can send the new results later.

The question is if you are using a BYOBReader and supply your ringbuffer..., the byob implementation can write directly to the buffer. This you can test.

> 
> Side and unrelated question: should we assume we need to use a packet ringbuffer for both client and server side components - for QUIC Streams?

For Webtransport stream, yes you have to do it on both sides. Otherwise, you will get bad surprises in real world scenarios.... (low data rate connection, many users....). 

> So far I have used it only on the client side which hasn't been a problem (my command packets are really small and sparse) but would like to be compliant.

You should do on both sides..., otherwise if load is high it will break your way of handling the stuff.

**Comment by martenrichter** [comment]
> I've got another question: if I wanted to also use BYOBReader on the client side. Let's say we pass a 4096 byte buffer to the reader ... can we assume the reader is using this as a RingBuffer? meaning we could potentially disregard the returned result from `read()` (aka the {done,value}) while assuming the reader appended the value in the buffer in a ringbuffer manner (overwriting eventually if we didn't read in time). We would just have to perform our our own READ_INDEX mechanism on the same buffer we provided .... ?

No it will just use the supplied bufferview for reading. The result will then a smaller view if the read is shorter. But shifting the view over your buffer is your responsibility. But it should be easy using byteOffset and byteLength of the bufferviews....

**Comment by benbenz** [comment]
> The question is if you are using a BYOBReader and supply your ringbuffer..., the byob implementation can write directly to the buffer. This you can test.

This is what I ran (basically part of your server code):

```

...

session.buffer = new Uint8Array(4096) ;

const listenBidi = async () => {

    try {
        const bidiReader = session.incomingBidirectionalStreams.getReader()

        const readerClosed = async () => {
            try {
                const err = await bidiReader.closed.catch(err => console.error ) ;
            } catch(e) {
                console.error(e) ;
            }
        }
        readerClosed() ;

        while (true) {
            try {
                const bidistr = await bidiReader.read().catch(err => console.error )
                if (bidistr.done) {
                    //console.log('bidiReader terminated')
                    break
                }
                if (bidistr.value) {
                    // ok we got a stream
                    const bidistream = bidistr.value
                    const reader = bidistream.readable.getReader()
                    const writer = bidistream.writable.getWriter() 
                    session.currentReader = reader ;
                    session.currentWriter = writer ;

                    while(true) {

                        const readdata = await reader.read(session.buffer).catch(err => console.error ) ;		

                        if(readdata.done) {
                            break ; 
                        }											
                        
                        if(!gotSID) { // first stream sent is the session/synth (for CTRL) or the SID (for MEDIA)
                            let sid = this.textDecoder.decode(readdata.value) ;
                            gotSID = true ;
                            quicListenerCallbacks.onQUICSession( session , sid ) ;
                        } else { // this is a normal command
                            if(quicListenerCallbacks.onQUICMessage) {
                                const onQUICMessageAsync = async (session,value) => {
                                    quicListenerCallbacks.onQUICMessage( session , readdata.value ) ;
                                }
                                onQUICMessageAsync( session , readdata.value ) ;
                            }
                        }

                        // echo the value
                        //writer.write(new Uint8Array(readdata.value)) ;
                    }

                    // echo it
                    //await bidistream.readable.pipeTo(bidistream.writable)
                    //console.log('bidiReader finished piping')
                }
            } catch(err) { console.error(err)} ;
        }
    } catch(err) { console.error(err)} ;
}
listenBidi()
```

I am not calling getBYOBReader cause I got an error on this call, is this correct?

**Comment by martenrichter** [comment]
>  I am not calling getBYOBReader cause I got an error on this call, is this correct?

I did not test the Byobreader, I just converted it to a bytestream, which simulates byob behaviour with autoallocate. 
So what is the error?

**Comment by benbenz** [comment]
The error was just that `getBYOBReader` method was not defined... Just wanted to make sure I just had to pass the buffer to the read() method (when the branch is activated) and that was pretty much the only change to perform, to activate BYOB mode...?

**Comment by martenrichter** [comment]
No you have to use getReader with the mode command set to byob see here:
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/getReader

**Comment by benbenz** [comment]
Ok so the latency goes to 1ms (instead of 0.92 ms). Pretty much the same.
I dont think the whole chain in the app grants this precision anyhow: I get pretty much the same value for each run of 500 pings, but - as you mentioned - there are quite some factors of uncertainty that should probably make us not worry about this kind of precision. As far as my app is concerned, I know that I have other overheads that are most representative of the latency and 1ms is more the precision level of latency that I am looking at (as opposed to 0.1ms).
On the other end, BYOB could help with garbage collection, if I understand correctly. This could prove very useful in time-critical jobs like media streaming ... I am not performing reads in the same Worker than the media server so this doesnt apply to my app, but I could see this being useful in other cases.

**Comment by martenrichter** [comment]
> Ok so the latency goes to 1ms (instead of 0.92 ms). Pretty much the same. I dont think the whole chain in the app grants this precision anyhow: I get pretty much the same value for each run of 500 pings, but - as you mentioned - there are quite some factors of uncertainty that should probably make us not worry about this kind of precision. As far as my app is concerned, I know that I have other overheads that are most representative of the latency and 1ms is more the precision level of latency that I am looking at (as opposed to 0.1ms). On the other end, BYOB could help with garbage collection, if I understand correctly. This could prove very useful in time-critical jobs like media streaming ... I am not performing reads in the same Worker than the media server so this doesnt apply to my app, but I could see this being useful in other cases.

Ok then, I will leave it as separate branch, and decide later...., should not be so hard to keep it in sync with the master branch.

**Comment by benbenz** [comment]
OK :) Thanks again. And thanks your precision regarding the standard/spec.

Testing things around, I think I had another seg fault during a network drop. I have another component that's bleeding edge so I don't know if it was webtransport or not, but - if you dont mind - we can keep this issue still open, and Ill add to it if I manage to catch/identify the issue.

**Comment by benbenz** [comment]
Another side question: are you able to create a BYOB Reader in Chrome?
I get the Type Error: `Uncaught (in promise) TypeError: Failed to execute 'getReader' on 'ReadableStream': Cannot use a BYOB reader with a non-byte stream`
I dont think we have control on how to create the ReadableStream for WebTransport, do we?

**Comment by martenrichter** [comment]
Hi,
I have included your changes to the development branch:
https://github.com/fails-components/webtransport/commit/2593ab4e0ec9279657e0dafd79902a1cb00f5896
I have to run some checks... and it will go into a new master branch and next package release.
