### ISSUE TITLE
No byob buffer support

### ISSUE THREAD

**Issue by martenrichter** [fails-components/webtransport#6]
Currently the streams are not a byte stream and byob is not support. May be buffer handling should be according to spec.

**Comment by martenrichter** [comment]
First implementation here https://github.com/fails-components/webtransport/tree/byobreader can be a regression compared to old implementation.

**Comment by davedoesdev** [comment]
I'm finding webtransport streams to be quite slow compared to http2 streams. Maybe byob would help, or is it the nature of the napi implementation with posted tasks and results?

**Comment by davedoesdev** [comment]
Data rate. I think it's fine actually. As a library to get things working while Node works on WebTransport in core, this project is great.

**Comment by martenrichter** [comment]
> As a library to get things working while Node works on WebTransport in core, this project is great.

And that is the whole intention..... I wrote it since I did not want to wait and I also did not want to base my new project on old protocols...
And I also do not mind if other developers step into the project and help to improve. And just need a working webtransport implementation for my avsrouter (https://github.com/fails-components/avsrouter) and client.

But anyway if it is datarate then one may try to look if the datarate depends on arraybuffer size, that could give a hint, where the bottleneck ist.

**Comment by martenrichter** [comment]
https://github.com/fails-components/webtransport/tree/byobreader

**Comment by martenrichter** [comment]
Support via byobreader using a shared memory buffer is coming. The new implementation has one additional memcopy, but does not malloc mem for every incoming buffer, and may reduce overhead.

**Comment by martenrichter** [comment]
https://github.com/fails-components/webtransport/commit/981d5aa6398233db12057552fbb74002bcc502d3

**Comment by frabera** [comment]
Awesome! Is it implemented also for datagrams?

**Comment by martenrichter** [comment]
No, the webtransport spec does not say anything about byobbuffer for datagrams. 
So for datagrams as before, a piece of memory is allocated for every datagram.
However, one can think of using a shared buffer also for this transfer and use the javascript side for allocating memory.

**Comment by martenrichter** [comment]
I have digged a bit. It seems chrome implements byob for datagrams already, but they forget at first to change the spec, but the change is already document and will soon go into spec, so I should be able to add datagram support as well.

**Comment by martenrichter** [comment]
Basic implementation is on the way
https://github.com/fails-components/webtransport/pull/186
more or less the same way Chrome does it, no it does not offer zero copy.
