### ISSUE TITLE
TypeError: res is not a function

### ISSUE THREAD

**Issue by benbenz** [fails-components/webtransport#7]
Hi marten,
Hope you are well. Just encountered this issue while switching between Stream and Datagram connections:

```
file:///Users/benoit/dev/webtransport/src/webtransport.js:423
    res()
    ^

TypeError: res is not a function
    at Http3WTSession.onDatagramSend (file:///Users/benoit/dev/webtransport/src/webtransport.js:423:5)
    at callback (file:///Users/benoit/dev/webtransport/src/webtransport.js:451:34)
```

I dont think you are storing resolve functions for Datagrams?

**Comment by martenrichter** [comment]
I do in the stream application, so that the ds stream waits for the datagrams which are send.
The error means, that a datagram was send, which was never initiated..... I think.. or it is already closed, so may be https://github.com/fails-components/webtransport/commit/c98abe5b170d73c252bf39041e156944512f53cb helps
Otherwise this is really weird
Can you add  something to log around line 254, and something to log at the error line. And may be in onClose...

**Comment by martenrichter** [comment]
Look for me like, the new commit should help.... (but it is untested).

**Comment by benbenz** [comment]
It seems this fixed this error. This causes another error that was on my todo list (suspecting this is at the app level). I will get back to you on this when I have more detail.

**Comment by benbenz** [comment]
This is probably unrelated in the end.
I had this error:
```
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".
```
This was because I was not doing a .catch() in some writer.write() with datagrams.
That said, once catching the error, it is null.

I dont know if what I am doing is right, but this error seems to be sourced to line 367 of webtransport.js: `this.outgoDatagramController.error(errorcode)`, which makes sense:
```
writableStreamDefaultWriterEnsureReadyPromiseRejected (internal/webstreams/writablestream:1008)
writableStreamStartErroring (internal/webstreams/writablestream:716)
writableStreamDefaultControllerError (internal/webstreams/writablestream:1166)
error (internal/webstreams/writablestream:537)
onClose (/Users/benoit/dev/webtransport/src/webtransport.js:367)
callback (/Users/benoit/dev/webtransport/src/webtransport.js:441)
```
That said, I think the 'error' available in the close function is not used/forwarded to the lower levels ... ? 
`function writableStreamDefaultWriterEnsureReadyPromiseRejected(writer, error) {` with `error` actually equal to 0 (zero)

**Comment by martenrichter** [comment]
The fix for this was only in the byob branch by accident, I have now also put the commit to master, sorry. https://github.com/fails-components/webtransport/commit/4e98dccf2af5a27884c64ff4001ee0e2e2166adc

**Comment by benbenz** [comment]
Ha great ! Thanks !

**Comment by benbenz** [comment]
Closing this issue. Those are not happening again :)

Still trying to get the SEGV error but I am not seeing it either :D
