### ISSUE TITLE
Client doesn't connect

### ISSUE THREAD

**Issue by davedoesdev** [fails-components/webtransport#76]
Hi-
I'm sure I must be doing something wrong in the test program below. I don't see the `Client ready` or `got a new session` messages.
As I say I'm sure I've just overooked something.

```js
import { readFile } from 'fs/promises';
import { X509Certificate } from 'crypto';
import { Http3Server, WebTransport } from '@fails-components/webtransport';

const cert = await readFile('/home/david/bpmux/test/certs/server.crt');

const server = new Http3Server({
    port: 8080,
    host: '127.0.0.1',
    secret: 'testsecret',
    cert,
    privKey: await readFile('/home/david/bpmux/test/certs/server.key')
});

(async () => {
    try {
        const session_stream = await server.sessionStream('/test');
        const session_reader = session_stream.getReader();

        const { done, value } = await session_reader.read();
        if (done) {
            return console.log('Server finished');
        }
        console.log('got a new session');
        await value.ready;
        console.log('server session is ready');
    } catch (ex) {
        console.error('Server error', ex);
    }
})();

server.startServer();

await new Promise(resolve => setTimeout(resolve, 2000));

const client = new WebTransport('https://127.0.0.1:8080/test', {
    serverCertificateHashes: [{
        algorithm: 'sha-256',
        value: Buffer.from(
            new X509Certificate(cert).fingerprint256.split(':').map(
                el => parseInt(el, 16)))
    }]
});
client.closed
    .then(() => { console.log('Connection closed'); })
    .catch(err => { console.error('Connection errored', err); });
console.log('Waiting for client to be ready');
await client.ready;
console.log('Client ready');

await client.createBidirectionalStream();
console.log('Client created stream');
```

**Comment by davedoesdev** [comment]
Btw, the cert and key were generated using the scripts [here](https://github.com/davedoesdev/bpmux/tree/master/test/certs)

**Comment by martenrichter** [comment]
I am not sure and I am currently away from computers, but I think the certificate validity is too long spec allows only 14 days( please check from memory) There may be other issues.

**Comment by davedoesdev** [comment]
@martenrichter @SnosMe yes they were the issues (14 days, algo) - many thanks for the pointer.
Is there a way I could have got that error thrown so it was possible to see what was wrong?
Thanks again for your help, appreciate it.

**Comment by martenrichter** [comment]
Well, I do not see that this information is currently easily exposed from the underlying lib ( btw. Chrome is also not helpful, diagnosing these issues), so I can not add this easily.
And since quiche changes its interface often, I try to not tap to deep into it.

**Comment by davedoesdev** [comment]
I can at least get a notification that something went wrong by handling the `catch` at https://github.com/fails-components/webtransport/blob/master/src/webtransport.js#L655
