### ISSUE TITLE
Install fails on LTS node

### ISSUE THREAD

**Issue by achingbrain** [fails-components/webtransport#91]
The `build.js` file uses import assertions, these fail on the present LTS node (16.x):

```console
% npm install @fails-components/webtransport
npm ERR! import pkg from './package.json' assert { type: 'json' }
npm ERR!                                  ^^^^^^
npm ERR! 
npm ERR! SyntaxError: Unexpected identifier
npm ERR!     at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)
npm ERR!     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)
npm ERR!     at async link (node:internal/modules/esm/module_job:67:21)
```

Node 16 is still a year away from end of life, is there any chance this can be refactored to work on node 16?

**Comment by martenrichter** [comment]
Actually, I am puzzled, that you say, that it does not work on node16.
Since I was using it yesterday in a Debian node16 container and had no problems (and I am still on node16 for my project), so it must be something else.

**Comment by achingbrain** [comment]
Ah no, all good I think - it depends on the minor of `v16` - it fails with `v16.13.0` but not with the latest `v16.18.0`.

**Comment by martenrichter** [comment]
Ok, perfect. My goal is that the package always works with the current active LTS and its most recent version.

**Comment by Banou26** [comment]
It seems like this error happens with (currently latest) nodejs 22.2.0 on windows

**Comment by martenrichter** [comment]
Yes, I can confirm this. It was always an experimental feature, so I have to check, what to do.

**Comment by martenrichter** [comment]
Reason seems to be that it is replaced with the `with` syntax, hopefully it is supported beginning from current LTS ...
https://groups.google.com/a/chromium.org/g/blink-dev/c/ZHvzLaJZRvo

**Comment by martenrichter** [comment]
Replacing `assert` with `with` solves the issue. PR is written, and it is now checked in CI/CD should then merge and trigger a new release.
