### ISSUE TITLE
Add types?

### ISSUE THREAD

**Issue by achingbrain** [fails-components/webtransport#93]
Would you accept a PR that adds types to the js part of this repo?

Either a) generated from JSDocs or b) conversion to typescript.

a) normally sounds like it'd be a smaller changeset but usually ends up more painful due to needing to unpick type conversions, null guarding on instance fields that aren't set in constructors etc and having to add `/** @type {foo} */` in loads of places.  b) is usually easier to work with going forwards and lets you express certain things more clearly (public interfaces, inheritance, etc).

**Comment by martenrichter** [comment]
I am generally open to including the types since it will make the life for people using TS easier.
Regarding a) or b), so far I have not looked at typescript, so I am not familiar with it.
On the other hand, the interface should be stable, since it tries to match the spec.
And of course, the types should match the current webtransport spec.

What I am not sure, what happens to the napi side,  types have side effects on this part. probably not?

**Comment by achingbrain** [comment]
> What I am not sure, what happens to the napi side

One approach is to [hand write the interfaces the native modules expose](https://stackoverflow.com/questions/44275172/typescript-declarations-file-for-node-c-addon) - a bit error prone but it's better than nothing.

**Comment by martenrichter** [comment]
> > What I am not sure, what happens to the napi side
> 
> One approach is to [hand write the interfaces the native modules expose](https://stackoverflow.com/questions/44275172/typescript-declarations-file-for-node-c-addon) - a bit error prone but it's better than nothing.

Or can one ignore this part, since the napi interfaces are never exposed to the outside world?

**Comment by achingbrain** [comment]
It's very tempting to say only the outside interface needs types, but `tsc` will verify the types are accurate - values returned have the correct fields and so on, which means they start to be applied internally as well.

At this point people usually decide to hand-roll the external types instead, which are rarely accurate and even if they are, tend to start diverging immediately.  The alternative is to mark everything internally as the `any` type which gives you absolutely nothing in terms of type safety and just adds noise everywhere.

For the c++ part, I'm not sure, something extracted from [nbind](https://www.npmjs.com/package/nbind) could help but I think this is less urgent since it's 100% internal.

I've typed the module using JSDoc locally, I'm just sanity checking it all against my use of the module in another project, when that's done I'll open a PR.

**Comment by martenrichter** [comment]
Well, `nbind` is for wasm and not for napi, I have to hand code everything with special napi functions, so this is a major point of divergence and it is runtime only. So tsc should not be able to check it, and some data is just passed through. That is why I think the focus should be on the external js and as you said it is less urgent.

The PR sounds good.

**Comment by achingbrain** [comment]
> Well, nbind is for wasm and not for napi,

I was attracted by this from the list of features, which is the thing I was referring to extracting, I didn't mean using the whole module..:

> Automatically generate TypeScript .d.ts definition files from C++ code for IDE autocompletion and compile-time checks of JavaScript side code.

**Comment by martenrichter** [comment]
But this is wasm compiling and not for real binaries as a node addon.
So a different story.
napi is a binary interface and wasm is a byte code for the browser.

**Comment by achingbrain** [comment]
Yes, agreed. The point is generating types from `.h` in a similar way to generating them from `.js`.  But again, not urgent as it's all internal.
